// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDp8MbahryPOXLDs9zfvOeNIrZ6pJEZB8M',
    appId: '1:583902623028:web:c028ad7cba0004499c2161',
    messagingSenderId: '583902623028',
    projectId: 'dmv-test-pro-dec47',
    authDomain: 'dmv-test-pro-dec47.firebaseapp.com',
    storageBucket: 'dmv-test-pro-dec47.appspot.com',
    measurementId: 'G-HY0C333SWL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_fd2IdlZkYLuhqpPOAcvfa8DfpeJSi3g',
    appId: '1:583902623028:android:fa14010e99e7ffa29c2161',
    messagingSenderId: '583902623028',
    projectId: 'dmv-test-pro-dec47',
    storageBucket: 'dmv-test-pro-dec47.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtHby7mxmVw1ADkBR_ZV9BnRKNOiuq2t8',
    appId: '1:583902623028:ios:60da5a0bc67aa5619c2161',
    messagingSenderId: '583902623028',
    projectId: 'dmv-test-pro-dec47',
    storageBucket: 'dmv-test-pro-dec47.appspot.com',
    iosClientId: '583902623028-at5l6nj1p1f45qb2bjc2rmp3bojdsrk1.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
